jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '88.0.4324.96'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run test
      run: |
        pip install -r requirements.txt &
        pip install -r app/requirements.txt &
        cd app &
        python3 flask-helloworld.py &
        cd .. &
        pytest selenium_example.py
